import Head from 'next/head';
import { ChangeEvent, FormEvent, useState } from 'react';
import Image from 'next/image';
import PingLogo from '../public/logo.svg';
import { FaFacebookF, FaTwitter, FaInstagram } from 'react-icons/fa';
import { BsCheckCircleFill } from 'react-icons/bs';

export default function Home() {
  const [email, setEmail] = useState<string>('');
  const [error, setError] = useState<boolean>(false);
  const [succesMsg, setSuccesMsg] = useState(false);

  const isValidEmail = (email: string): boolean => {
    return /\S+@\S+\.\S+/.test(email);
  };

  const handleChange = (e: ChangeEvent<HTMLInputElement>): void => {
    if (!isValidEmail(email)) {
      setError(true);
    } else {
      setError(false);
    }
    setEmail(e.target.value);
  };

  const handleSubmit = (e: FormEvent<HTMLFormElement>): void => {
    e.preventDefault();
    if (!error && email.length > 0) {
      setEmail('');
      setError(false);
      setSuccesMsg(true);
      console.log('submit');
    } else {
      setError(true);
    }
  };

  return (
    <>
      <Head>
        <title>Frontend Mentor | Ping coming soon page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="mx-auto w-[375px] p-12 md:w-[540px]">
        <header className="flex items-center justify-center py-10">
          <Image src={PingLogo} alt="Ping" />
        </header>
        {succesMsg ? (
          <div className="mx-auto mt-10 mb-20 flex flex-col items-center justify-center gap-4">
            <h2 className="text-2xl italic text-gray">
              You are now suscribed!
            </h2>
            <span className="text-5xl text-green-600">
              <BsCheckCircleFill />
            </span>
          </div>
        ) : (
          <>
            <section className="space-y-4 text-center ">
              <h2 className="text-2xl tracking-wide text-gray md:text-3xl">
                We are launching{' '}
                <span className="font-bold text-veryDarkBlue"> soon!</span>
              </h2>
              <p>Subscribe and get notified</p>
            </section>
            <form
              className="my-10 flex flex-col items-start gap-4 md:flex-row"
              onSubmit={handleSubmit}
            >
              <div className="flex w-full flex-col gap-1 md:w-2/3">
                <input
                  type="email"
                  placeholder="Your email address ..."
                  className={error ? 'input-email error-email' : 'input-email'}
                  onChange={handleChange}
                />
                {error ? (
                  <span className="w-full text-center text-xs italic text-lightRed md:px-8 md:text-left">
                    Please provide a valid email address
                  </span>
                ) : null}
              </div>
              <button
                type="submit"
                className="h-10 w-full rounded-full bg-blue text-sm font-semibold text-white drop-shadow-md transition-all duration-200 ease-in-out hover:opacity-80 md:h-12 md:w-1/3"
                disabled={error ? true : false}
              >
                Notify Me
              </button>
            </form>
          </>
        )}

        <section className="relative h-[200px] w-full p-4 md:h-[385px]">
          <Image src="/illustration-dashboard.png" alt="Dashboard" fill />
        </section>
      </main>
      <footer className="mx-auto mt-4 p-4 text-center">
        <div className="space-y-8">
          <section className="flex items-center justify-center gap-4 text-sm text-blue">
            <div className="flex h-8 w-8 items-center justify-center rounded-full outline outline-1 outline-paleBlue drop-shadow-lg">
              <FaFacebookF />
            </div>
            <div className="flex h-8 w-8 items-center justify-center rounded-full outline outline-1 outline-paleBlue drop-shadow-lg">
              <FaTwitter />
            </div>
            <div className="flex h-8 w-8 items-center justify-center rounded-full outline outline-1 outline-paleBlue drop-shadow-lg">
              <FaInstagram />
            </div>
          </section>
          <section className="text-xs">
            &copy; Copyrught Ping. All rights reserved.
          </section>
        </div>
        <div className="mt-6">
          <p className="text-sm">
            Challenge by{' '}
            <a
              href="https://www.frontendmentor.io?ref=challenge"
              target="_blank"
              rel="noreferrer"
            >
              Frontend Mentor
            </a>
            . <br className="md:hidden" /> Coded by{' '}
            <a
              href="https://github.com/iamcgs"
              className="font-semibold text-blue hover:opacity-75"
            >
              Carla
            </a>
            .
          </p>
        </div>
      </footer>
    </>
  );
}
